
mybatis:
  mapper-locations:
    - config/mapper/*
  type-aliases-package: fun.oook.webchat.model
  #  type-handlers-package: fun.oook.webchat.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30


spring:
  devtools:
    restart:
      enabled=true:
  mvc:
    view:
#      prefix: classpath:/static
      suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost/~/.h2/test/test
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: false
      path: /console
      settings:
        trace: false
        web-allow-others: false

logging:
  level:
    web:
      DEBUG
    fun:
      oook:
        one:
          mapper: DEBUG

debug: true
